# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
array_1d = np.array([1,2,3])
# Create a 2-dimensional NumPy array using np.array()
array_2d = np.array([[1,2,3],
                     [4,5,6]])
# Create a 3-dimensional Numpy array using np.array()
array_3d = np.array([[[1,2,3],
                      [4,5,6],
                      [7,8,9]],
                     [[10,11,12],
                      [13,14,15],
                      [16,17,18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
array_1d.shape, array_1d.ndim, array_1d.dtype, array_1d.size, type(array_1d)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
array_2d.shape, array_2d.ndim, array_2d.dtype, array_2d.size, type(array_2d)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
array_3d.shape, array_3d.ndim, array_3d.dtype, array_3d.size, type(array_3d)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(array_2d)
df

0  1  2
0  1  2  3
1  4  5  6

In [7]:
# Create an array of shape (10, 2) with only ones
array_ones = np.ones((10,2))
array_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
array_zeros = np.zeros((7,2,3))
array_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
array_range = np.arange(0, 100, 3)
array_range

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
array_random = np.random.randint(0, 10, size=(7,2))
array_random

array([[3, 1],
       [6, 0],
       [0, 7],
       [1, 8],
       [2, 7],
       [3, 9],
       [6, 1]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array_2 = np.random.rand(3, 5)
random_array_2

array([[0.97904906, 0.26549082, 0.045748  , 0.87840819, 0.66344802],
       [0.23309547, 0.18522054, 0.57433384, 0.53131713, 0.08308293],
       [0.99470058, 0.80703775, 0.34356622, 0.41816846, 0.15367738]])

In [14]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_3 = np.random.randint(0, 10, size=(4,6))
random_array_3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [15]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array_4 = np.random.randint(1, 10, size=(3,7))

# Find the unique numbers in the array you just created
np.unique(random_array_4)

array([1, 2, 3, 4, 5, 7, 9])

In [21]:
# Find the 0'th index of the latest array you created
random_dataframe = pd.DataFrame(random_array_4)
random_dataframe.loc[0]

0    9
1    1
2    3
3    7
4    4
5    9
6    3
Name: 0, dtype: int64

In [39]:
# Get the first 2 rows of latest array you created
random_array_4[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [40]:
# Get the first 2 values of the first 2 rows of the latest array
random_array_4[:2][0][:2]

array([9, 1])

In [41]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array_5 = np.random.randint(0, 10, size=(3,5))
ones_array = np.ones((3,5))

In [42]:
# Add the two arrays together
random_array_5 + ones_array

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [44]:
# Create another array of ones of shape (5, 3)
ones_array_2 = np.ones((5,3))

In [47]:
# Try add the array of ones and the other most recent array together
ones_array * ones_array_2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [48]:
# Create another array of ones of shape (3, 5)
ones_array_3 = np.ones((3,5))

In [52]:
# Subtract the new array of ones from the other most recent array
ones_array_3 - ones_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
# Multiply the ones array with the latest array
ones_array * ones_array_3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
# Take the latest array to the power of 2 using '**'
random_array_5 ** 2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [56]:
# Do the same thing with np.square()
np.square(random_array_5)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [55]:
# Find the mean of the latest array using np.mean()
np.mean(random_array_5)

3.8666666666666667

In [59]:
# Find the maximum of the latest array using np.max()
np.max(random_array_5)

9

In [60]:
# Find the minimum of the latest array using np.min()
np.min(random_array_5)

0

In [61]:
# Find the standard deviation of the latest array
np.std(random_array_5)

2.578543947441829

In [62]:
# Find the variance of the latest array
np.var(random_array_5)

6.648888888888889

In [67]:
# Reshape the latest array to (3, 5, 1)
random_array_5.shape
random_array_5_reshaped = np.reshape(random_array_5, (3,5,1))
random_array_5_reshaped.shape

(3, 5, 1)

In [69]:
# Transpose the latest array
random_array_5_reshaped.T.shape

(1, 5, 3)

What does the transpose do?

In [72]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_array_6 = np.random.randint(0, 10, size=(3,3))
random_array_7 = np.random.randint(0, 10, size=(3,2))

In [73]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array_6,random_array_7)

array([[ 57,  49],
       [128, 135],
       [ 42,  68]])

In [74]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_array_8 = np.random.randint(0, 10, size=(4,3))
random_array_9 = np.random.randint(0, 10, size=(4,3))

In [75]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array_8,random_array_9)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [76]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
random_array_10 = random_array_8.T
np.dot(random_array_9,random_array_10)

array([[  7,  14,  69,  62],
       [ 56,  40, 153, 140],
       [ 28,  36, 111, 100],
       [ 14,  10,  57,  52]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [77]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
random_array_11 = np.random.randint(0, 10, size=(3,4))
random_array_12 = np.random.randint(0, 10, size=(3,4))

In [78]:
# Compare the two arrays with '>'
random_array_11 > random_array_12

array([[False,  True, False, False],
       [False,  True, False,  True],
       [ True,  True,  True,  True]])

What happens when you compare the arrays with `>`?

In [79]:
# Compare the two arrays with '>='
random_array_11 >= random_array_12

array([[False,  True, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [80]:
# Find which elements of the first array are greater than 7
random_array_11 > 7

array([[False, False, False, False],
       [False,  True, False, False],
       [ True,  True,  True, False]])

In [81]:
# Which parts of each array are equal? (try using '==')
random_array_11 == random_array_12

array([[False, False, False, False],
       [ True, False,  True, False],
       [False, False, False, False]])

In [84]:
# Sort one of the arrays you just created in ascending order
np.sort(random_array_12)

array([[0, 3, 3, 6],
       [3, 4, 6, 6],
       [1, 2, 5, 6]])

In [85]:
# Sort the indexes of one of the arrays you just created
np.argsort(random_array_12)

array([[1, 2, 3, 0],
       [3, 0, 1, 2],
       [3, 1, 2, 0]])

In [86]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(random_array_11)

5

In [87]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(random_array_11)

3

In [88]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(random_array_11, axis=1)

array([1, 1, 1])

In [89]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(random_array_11, axis=0)

array([0, 0, 0, 0])

In [99]:
# Create an array of normally distributed random numbers
normal_array = np.random.normal(size=(3,4))
normal_array

array([[-0.48312268, -0.56982835, -2.09159967,  1.26374053],
       [-0.01548334, -0.02737645,  0.81787351, -1.05460447],
       [-0.75832712,  0.45741565, -0.06437805,  0.34490234]])

In [102]:
# Create an array with 10 evenly spaced numbers between 1 and 100
range_array = np.arange(1, 100, 10)
range_array

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.